config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root :to => "displacements#index" 

  resources :displacements
  resources :cars
  resources :addresses
  resources :functionaries


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/displacement.rb
class Displacement < ApplicationRecord
  belongs_to :car
  belongs_to :functionary
  belongs_to :addressSrc, class_name: "Address"
  belongs_to :addressDst, class_name: "Address"
  
  validates :car_id, :functionary_id, :dateDay, :osNumber,
            :osProject, :startHour, :addressSrc_id,
            :addressDst_id, :kmStart, presence: true
  
  validate :km_end_start, :addressEqual , :hour_end_start 
  before_save :set_km_count, :set_velocity_medium
  after_save :km_update
  enum osProject: [ :SOLUTIS, :SEFAZ, :SEC, :TJBA, :EBAL, :BAHIAGÁS, :UFBA, :IRDEB, :MP  ]
  
  filterrific(
   default_filter_params: { sorted_by: 'dateDay_desc' },
   available_filters: [
      :sorted_by,      
      :with_dateDay_gte,
      :with_dateDay_lt,
      :with_project,
      :with_functionary_id
   ]
  )
 # define ActiveRecord scopes for
 # :search_query, :sorted_by, :with_country_id, and :with_created_at_gte
  
  
  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s      
    when /^id_/
      order("displacements.id #{ direction }")
    when /^dateDay_/
      order("displacements.\"dateDay\" #{ direction }","displacements.\"startHour\" desc") 
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
  
  scope :with_dateDay_gte,lambda { |reference_time|
    where('displacements."dateDay" >= ?', reference_time)
  }

  scope :with_dateDay_lt,lambda { |reference_time|
    where('displacements."dateDay" <= ?', reference_time)
  }
  
  scope :with_functionary_id, lambda {|functionary_ids|
    where(functionary_id: [*functionary_ids])
  }
 
  scope :with_project, lambda {|project|
    where(osProject: project)
  } 

  scope :with_displacement, ->(user){
    includes(:functionary,:addressDst)
    .joins("INNER JOIN functionaries ON functionaries.id = displacements.functionary_id")
    .where("functionary_id = ? OR leader = ?", user.functionary, user.functionary)
  }
  
  scope :with_displacement_csv, ->(functionary_id, dateStart, dateEnd) { 
    where('functionary_id = ? AND "dateDay" BETWEEN ? and ?', functionary_id, dateStart, dateEnd)
  }

  def self.options_for_sorted_by
    [
      ['Id', 'id_desc'],
      ['Data', 'dateDay_desc']
    ]
  end
  
  def addressEqual    
    if self.addressSrc == self.addressDst      
      errors.add(:base, "Endereço de Origem não pode ser igual ao de Destino !")
    end    
  end
  
  def km_end_start    
    if km_end_less?      
      errors.add(:base, "Kilometragem final menor que inicial!")
    end    
  end
  
  def km_end_less?
    unless kmEnd.blank? || kmEnd.nil?
      kmEnd < kmStart
    end
  end

  def hour_end_start    
    if hour_end_less?      
      errors.add(:base, "Hora chegada não é maior que a hora de partida!")
    end    
  end

  def hour_end_less?
    unless endHour.blank? || endHour.nil?
      endHour <= startHour
    end
  end
  
  def set_km_count
    unless kmEnd.blank? || kmEnd.nil? || kmStart.blank? || kmStart.nil?
      unless km_end_less?
        self.kmCount = kmEnd - kmStart
      end
    else
      self.kmCount = nil
      self.velocity = nil
    end
  end 

  def set_velocity_medium    
    unless kmCount.nil? || startHour.nil? || endHour.nil?
      self.velocity = self.kmCount / ((self.endHour -  self.startHour)/3600)
    end
  end
 
  def total_blank?    
     self.kmEnd.blank? || self.kmEnd.nil? || self.endHour.blank? || self.endHour.nil?
  end

  def km_update

    car = Car.find(self.car_id)

    if car.km.nil? || car.km.blank?
      car.km = 0
    end  

    if self.kmEnd.nil? || self.kmEnd.blank?
      self.kmEnd = 0
    end

    if car.km < self.kmEnd
      car.update(km: self.kmEnd)
    end

  end

end

app/controllers/displacements_controller.rb
class DisplacementsController < ApplicationController
  before_action :set_displacement, only: [:show, :edit, :update, :destroy]
  before_action :lists_selects, only: [:edit, :update, :create, :new]
  
  #Cancancan
  load_and_authorize_resource
  
  # GET /displacements
  # GET /displacements.json
  def index

    if  request.format == "csv"
      @displacements_csv =  Displacement.with_displacement_csv(params[:p1], params[:p2], params[:p3]).order(:dateDay, :startHour)
    end
    
    @filterrific = initialize_filterrific(
        Displacement.with_displacement(current_user),
        params[:filterrific],
        select_options: {
          with_project: Displacement::osProjects,
          sorted_by: Displacement.options_for_sorted_by,
          with_functionary_id: Functionary.with_functionary(current_user).options_for_select
        
        },
        default_filter_params: {
          with_dateDay_gte: Date.today,
          with_dateDay_lt: Date.today,
          sorted_by: 'dateDay_desc'
        },
        persistence_id: false,
      ) or return

      @displacements = @filterrific.find.page(params[:page])

      rescue ActiveRecord::RecordNotFound => e
        # There is an issue with the persisted param_set. Reset it.
        puts "Had to reset filterrific params: #{ e.message }"
        redirect_to(reset_filterrific_url(format: :html)) and return
    
    respond_to do |format|
      format.html      
      format.csv { render :csv => @displacements_csv}
    end

  end

  # GET /displacements/1
  # GET /displacements/1.json
  def show
  end

  # GET /displacements/new
  def new
    @displacement = Displacement.new
  end

  # GET /displacements/1/edit
  def edit
  end

  # POST /displacements
  # POST /displacements.json
  def create
    @displacement = Displacement.new(displacement_params)

    respond_to do |format|
      if @displacement.save
        format.html { redirect_to @displacement, notice: I18n.t('messages.created_with', item: (Displacement.model_name.human count: 1) )}
        format.json { render :show, status: :created, location: @displacement }
      else
        format.html { render :new }
        format.json { render json: @displacement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /displacements/1
  # PATCH/PUT /displacements/1.json
  def update
    respond_to do |format|
      if @displacement.update(displacement_params)
        format.html { redirect_to @displacement, notice: I18n.t('messages.updated_with', item: (Displacement.model_name.human count: 1)  )}
        format.json { render :show, status: :ok, location: @displacement }
      else
        format.html { render :edit }
        format.json { render json: @displacement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /displacements/1
  # DELETE /displacements/1.json
  def destroy
    @displacement.destroy
    respond_to do |format|
      format.html { redirect_to displacements_url, notice: I18n.t('messages.destroyed_with', item: (Displacement.model_name.human count: 1) )}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_displacement
      @displacement = Displacement.find(params[:id])      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def displacement_params
      params.require(:displacement).permit(:car_id, :functionary_id, :dateDay, :osNumber, :osProject, :startHour, :endHour, :addressSrc_id, :addressDst_id, :kmStart, :kmEnd, :kmCount, :annotation, :velocity)
    end
    
    def lists_selects
      @list_addressess = Address.with_address(current_user)
      @list_functionaries = Functionary.with_functionary(current_user)
    end
   
end

app/helpers/displacements_helper.rb
module DisplacementsHelper

  def velocity_km(velocity)  
    unless velocity.nil? || velocity.blank?
      if velocity > 100
        "<span class='text-danger'> #{velocity.ceil.to_s << ' Km/h'} </span>".html_safe 
      else
        velocity.ceil.to_s << ' Km/h'
      end
    end 
  end

end

app/views/displacements/_form.html.erb
<%= form_with(model: displacement, local: true) do |form| %>
  <% if displacement.errors.any? %>
    <% displacement.errors.full_messages.each do |message| %>
        <%= javascript_tag  "toastr['error']('#{message}')"  %>
      <% end %>
  <% end %>

  <div class="form-row">
    <div class="form-group col-xs-12 col-sm-12 col-md-4">
      <%= form.label :car_id %>      
     <% options = option_groups_from_collection_for_select(@list_functionaries, :cars, :name, :id, :full_car_name, @displacement.car_id) %>
     <%= form.select :car_id,   options, {}, {:class => "form-control"}  %>
    </div>

    <div class="form-group col-xs-12 col-sm-12 col-md-8">
     <%= form.label :functionary_id %>
     <% options = options_from_collection_for_select(@list_functionaries, 'id', 'name', @displacement.functionary_id ) %>
     <%= form.select :functionary_id,   options, {}, {:class => "form-control"}  %>
    </div>
  </div>

  <div class=" form-row">
    <div class="form-group col-xs-12 col-sm-12 col-md-4">
      <%= form.label :dateDay %>
      <%= form.date_select :dateDay,  {}, {:class => "form-control" }  %>
    </div>

    <div class="form-group col-xs-12 col-sm-12 col-md-4">
      <%= form.label :osNumber %>
      <%= form.number_field :osNumber, :class => "form-control" %>
    </div>

    <div class="form-group col-xs-12 col-sm-12 col-md-4">
      <%= form.label :osProject %>
      <%= form.select :osProject, Displacement::osProjects.collect { |p| p[0] }, {}, {:class => "form-control", :selected => 1}  %>


    </div>
  
  </div>

  <div class="form-row">
    <div class="form-group col-xs-12 col-sm-12 col-md-2">
      <%= form.label :startHour %>
      <%= form.time_field :startHour, :class => "form-control"  %>
    </div>
    
    <div class="form-group col-xs-12 col-sm-12 col-md-2">
      <%= form.label :kmStart %>
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">
            <span onclick="getLastKm()"><i class="fas fa-route"></i></span>
          </div>
        </div>
        <%= form.number_field :kmStart, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group col-xs-12 col-sm-12 col-md-8">
      <%= form.label :addressSrc_id %>    
      <% options = options_from_collection_for_select(@list_addressess, 'id', 'description', @displacement.addressSrc_id) %>
      <%= form.select :addressSrc_id,   options, {}, {:class => "form-control"}  %>
    </div>
  </div>
  <div class="form-row">

    <div class="form-group col-xs-12 col-sm-12 col-md-2">
      <%= form.label :endHour %>
      <%= form.time_field :endHour, :class => "form-control" %>
    </div>
  

    <div class="form-group col-xs-12 col-sm-12 col-md-2">
      <%= form.label :kmEnd %>
      <%= form.number_field :kmEnd, :class => "form-control" %>
    </div>

  <div class="form-group col-xs-12 col-sm-12 col-md-8">
    <%= form.label :addressDst_id %>   
    <% options = options_from_collection_for_select(@list_addressess, 'id', 'description', @displacement.addressDst_id) %>
    <%= form.select :addressDst_id,   options, {}, {:class => "form-control"}  %>
    
  </div>
 </div>

  <div class="form-row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12">
      <%= form.label :annotation %>
      <%= form.text_area :annotation, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= link_to t('buttons.back'), displacements_path, class:"btn btn-success" %>
    <%= submit_tag t('buttons.save'),  class:"btn btn-primary" %>
  </div>

<% end %>

app/views/displacements/_list.html.erb
<div id="filterrific_results">

 <div class="row mt-3"> 
    <div class="col-md-12"> 
      <label><i>Selecione o Funcionário, Data Início e Data Fim antes de exportar o arquivo.</i></label><br /> 
      <%= link_to( 'CSV', displacements_path(format: :csv, p1: @filterrific.with_functionary_id, p2: @filterrific.with_dateDay_gte, p3: @filterrific.with_dateDay_lt), {class: "btn btn-sm btn-outline-primary" } ) %>
      <%= link_to( 'PDF', displacements_path(format: :csv, p1: @filterrific.with_functionary_id, p2: @filterrific.with_dateDay_gte, p3: @filterrific.with_dateDay_lt), {class: "btn btn-sm btn-outline-danger" } ) %>
    </div>
</div>

<div  class="table-striped table-sm table-responsive table-hover mt-3">
  <table class="table">
    <caption> <%= page_entries_info displacements %> </caption>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"><%= filterrific_sorting_link(@filterrific, :dateDay) %></th>        
        <th scope="col"><%= Displacement.human_attribute_name("osNumber") %></th>
        <th scope="col"><%= Displacement.human_attribute_name("osProject" )%></th>
        <th scope="col"><%= Displacement.human_attribute_name("startHour") %></th>
        <th scope="col"><%= Displacement.human_attribute_name("kmEnd") %></th>
        <th scope="col"><%= Displacement.human_attribute_name("addressDst") %></th>
        <% if %w[leader].include? current_user.functionary.function %>
          <th scope="col"><%= Displacement.human_attribute_name("functionary_id") %></th>
        <% end %>
      </tr>
    </thead>
 
    <!-- Reload Link line table  -->
    <%= javascript_tag '    
      jQuery(document).ready(function($) {
          $(".clickable-row").click(function() {
              window.location = $(this).data("href");
          });
      });
    '%>
    
    <tbody >
      <% displacements.each do |displacement| %>
      <tr class='clickable-row <%= "table-warning" if displacement.total_blank?  %>' data-href='<%=  displacement_path(displacement) %>' >
          <td scope="row"><%= displacement.id %> </td>
          <td><%= l displacement.dateDay %></td>
          <td><%= displacement.osNumber %></td>
          <td><%= displacement.osProject %></td>
          <td><%= displacement.startHour.strftime("%H:%M") unless displacement.startHour.nil?  %></td>
          <td><%= displacement.kmEnd %></td>  
          <td ><%= displacement.addressDst.description %></td> 
          <% if %w[leader].include? current_user.functionary.function %> 
            <td><%= displacement.functionary.name %></td>  
          <% end %>         
        </tr>      
      <% end %>
    </tbody>
  </table>
  </div>
  <div class="row">
    <div class="col-12" >
      <%= paginate displacements %>
    </div>
  </div>

</div>  

app/views/displacements/edit.html.erb
<h1 ><i class="fas fa-location-arrow"></i><%= " Editar #{Displacement.model_name.human}: #{@displacement.id} " %></h1>

<%= render 'form', displacement: @displacement %>

app/views/displacements/index.csv.erb
<%- headers = [        
        Displacement.human_attribute_name("dateDay"),
        Displacement.human_attribute_name("osNumber"),
        Displacement.human_attribute_name("osProject"),
        Displacement.human_attribute_name("startHour"),
        Displacement.human_attribute_name("addressSrc"),
        Displacement.human_attribute_name("kmStart"),
        Displacement.human_attribute_name("addressDst"),
        Displacement.human_attribute_name("kmEnd"),
        Displacement.human_attribute_name("endHour"),
        Displacement.human_attribute_name("kmCount"),
        'R$/km rodado',
        Displacement.human_attribute_name("annotation")
  ] -%>
<%= CSV.generate_line headers, :col_sep => "|", row_sep: "\r\n",  encoding: "ISO8859-1" %>
<%- @displacements_csv.each do |d| -%>  
  <%= CSV.generate_line([
            (l d.dateDay),
            d.osNumber,
            d.osProject,
            (d.startHour.strftime("%H:%M") unless d.startHour.nil?),
            full_address(d.addressSrc),
            d.kmStart,
            full_address(d.addressDst),
            d.kmEnd,
            (d.endHour.strftime("%H:%M") unless d.endHour.nil?),
            nil,
            nil,
            (d.annotation )
    ], row_sep: "\r\n", :col_sep => "|", :quote_char =>  " ",  encoding: "ISO8859-1") -%>
<%- end -%>

app/views/displacements/index.html.erb
<h1><i class="fas fa-location-arrow"></i> <%= Displacement.model_name.human count: 2 %></h1>

<% if can? :create, Displacement %>
  <%= link_to new_displacement_path do %>
      <span class="pull-left">
        <i class="far fa-lg fa-plus-square"></i> 
        <%= t('buttons.new') << ' ' << Displacement.model_name.human %>
      </span>
  <% end %>
<% end %>

<%= form_for_filterrific @filterrific do |f| %>

  <div class="well">
    <div class="row">

      <div class="col-md-3">
        <%= f.label t('labels.sorted_by') %>
        <%= f.select(
          :sorted_by, @filterrific.select_options[:sorted_by],
           {}, { :class => 'form-control' }
            ) %>
      </div>
      
      <div class="col-md-3">
        <%= f.label Displacement.human_attribute_name("osProject") %>
        <%= f.select(
          :with_project,
          @filterrific.select_options[:with_project],
          {include_blank: '- Qualquer -'}, { :class => 'form-control' }
        ) %>
      </div>

      <div class="col-md-3">
        <%= f.label t('labels.date_first') %>
        <%= f.date_field(:with_dateDay_gte, class: 'form-control ') %>
      </div>

      <div class="col-md-3">
        <%= f.label t('labels.date_finish') %>
        <%= f.date_field(:with_dateDay_lt, class: 'form-control') %>
      </div>

    </div>

    <div class="row">  
      <div class="col-md-6">
        <%= f.label Displacement.human_attribute_name("functionary_id") %>
        <%= f.select(
          :with_functionary_id,
          @filterrific.select_options[:with_functionary_id],
          {include_blank: '- Qualquer -'}, { :class => 'form-control'}
        ) %>
      </div>

      <div class="col-md-4">
        <%= f.label "Opções"%><br />
        <%= link_to( t('buttons.reset_filter'), reset_filterrific_url, class:"btn btn-outline-primary") %>
      </div>

    </div>

  </div>
  <%= render_filterrific_spinner %> 
  
<% end %>

<%= render partial:'displacements/list', locals: { displacements: @displacements } %>

app/views/displacements/index.js.erb
<% js = escape_javascript(
  render(partial: 'displacements/list', locals: { displacements: @displacements })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/displacements/new.html.erb
<h1 ><i class="fas fa-location-arrow"></i><%= " Nova #{Displacement.model_name.human}" %></h1>

<%= render 'form', displacement: @displacement %>

app/views/displacements/show.html.erb
<h1 ><i class="fas fa-location-arrow"></i><%= " #{Displacement.model_name.human}: #{@displacement.id} " %></h1>
  
  <div class="row">
    <div class="col-md-8"> 
      <div id="map"></div>
      <div class="mb-4">  
        <%= link_to "Ver no Google", "https://www.google.com/maps/dir/?api=1&origin=#{@displacement.addressSrc.geolocalization}&destination=#{@displacement.addressDst.geolocalization}", {class: "btn btn-sm btn-outline-secondary", target: "_blank", rel: "external"} %>
      </div>
   </div> 

    <div class="col-md-4">      
        <p>
          <strong><%= Displacement.human_attribute_name("car_id") %>: </strong>
          <%= link_to full_car(@displacement.car), car_path(@displacement.car) %> 
          </p>
        <p>
          <strong><%= Displacement.human_attribute_name("functionary_id") %>: </strong>
          <%= link_to @displacement.functionary.name, functionary_path(@displacement.functionary) %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("dateDay") %>: </strong>
          <%= l @displacement.dateDay%>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("osNumber") %>: </strong>
          <%= @displacement.osNumber %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("osProject") %>: </strong>
          <%= @displacement.osProject %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("startHour") %>: </strong>
          <%= @displacement.startHour.strftime("%H:%M") unless @displacement.startHour.nil?   %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("endHour") %>:</strong>
          <%= @displacement.endHour.strftime("%H:%M")  unless @displacement.endHour.nil?  %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("addressSrc") %>:</strong>
          <%= link_to full_address(@displacement.addressSrc), address_path(@displacement.addressSrc) %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("addressDst") %>:</strong>
          <%= link_to full_address(@displacement.addressDst), address_path(@displacement.addressDst) %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("kmStart") %>:</strong>
          <%= @displacement.kmStart %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("kmEnd") %>:</strong>
          <%= @displacement.kmEnd %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("kmCount") %>:</strong>
          <%= @displacement.kmCount %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("velocity") %>:</strong>
          <%= velocity_km(@displacement.velocity) %>
        </p>
        <p>
          <strong><%= Displacement.human_attribute_name("annotation") %>:</strong>
          <%= @displacement.annotation %>
        </p>

    </div>
  </div>


<div class="form-group  text-center d-print-none ">
  <% if can? :index, Displacement %>
    <%= link_to t('buttons.back'), displacements_path, class:"btn btn-sm btn-success" %>
 <% end %>
  <% if can? :update, Displacement %>
    <%= link_to t('buttons.edit'), edit_displacement_path(@displacement), class:"btn btn-sm btn-primary" %>
  <% end %>  
  <% if can? :destroy, Displacement %>
    <%= link_to t('buttons.delete'), displacement_path(@displacement), method: :delete, data: { confirm:  I18n.t('messages.confirm_with',item: " #{Displacement.model_name.human}: #{@displacement.id} " )}, class: "btn btn-sm btn-danger" %>
  <% end %>
</div>

  <div id="srcLocal" class="d-none"> 
    <%= @displacement.addressSrc.geolocalization %>
  </div>
  <div id="dstLocal" class="d-none">
    <%= @displacement.addressDst.geolocalization %>
  </div>