config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root :to => "displacements#index" 

  resources :displacements
  resources :cars
  resources :addresses
  resources :functionaries


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/functionary.rb
class Functionary < ApplicationRecord

  has_many :cars
  has_many :addresses
  has_many :displacements, dependent: :delete_all
  belongs_to :user, inverse_of: :functionary, optional: true
  accepts_nested_attributes_for :user, reject_if: :all_blank
  
  validates :name, :matriculation, :function, 
            :leader,  presence: true

  enum function: [ :leader, :tecnical ]

  scope :with_functionary, ->(current_user){
    where("id = ? OR leader = ?", current_user, current_user)
    .order(:name)
  }
  
  def self.options_for_select
    order('LOWER(name)').map { |e| [e.name, e.id] }
  end

end

app/controllers/functionaries_controller.rb
class FunctionariesController < ApplicationController
  before_action :set_functionary, only: [:show, :edit, :update, :destroy]
  before_action :lists_selects, only: [:edit, :create, :new, :update]
  
  #Cancancan
  load_and_authorize_resource

  #Ex:- :default =>''
  # GET /functionaries
  # GET /functionaries.json
  def index
    @functionaries = Functionary.with_functionary(current_user).page params[:page]
   
  end

  # GET /functionaries/1
  # GET /functionaries/1.json
  def show
  end

  # GET /functionaries/new
  def new
    @functionary = Functionary.new
    @functionary.build_user
  end

  # GET /functionaries/1/edit
  def edit
  end

  # POST /functionaries
  # POST /functionaries.json
  def create
    @functionary = Functionary.new(functionary_params)
    respond_to do |format|
      if @functionary.save
        format.html { redirect_to @functionary, notice: I18n.t('messages.created_with', item: (Functionary.model_name.human count: 1) )}
        format.json { render :show, status: :created, location: @functionary }
      else
        format.html { render :new }
        format.json { render json: @functionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /functionaries/1
  # PATCH/PUT /functionaries/1.json
  def update
    respond_to do |format|
      if @functionary.update(functionary_params)
        format.html { redirect_to @functionary, notice: I18n.t('messages.updated_with', item: (Functionary.model_name.human count: 1)  ) }
        format.json { render :show, status: :ok, location: @functionary }
      else
        format.html { render :edit }
        format.json { render json: @functionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functionaries/1
  # DELETE /functionaries/1.json
  def destroy
    @functionary.destroy
    respond_to do |format|
      format.html { redirect_to functionaries_url, notice:  I18n.t('messages.destroyed_with', item: (Functionary.model_name.human count: 1) ) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_functionary
      @functionary = Functionary.find(params[:id])
    end

    def lists_selects
      @list_leaders = Functionary.where(function:  :leader).order(:name).select(:id, :name)
    end
 
    # Never trust parameters from the scary internet, only allow the white list through.
    def functionary_params
      params.require(:functionary).permit(
        :matriculation, :name, :function, :active, :leader, 
        :user_attributes => [:id, :email, :password, :password_confirmation]
      ) 
    end
end

app/helpers/functionaries_helper.rb
module FunctionariesHelper
  
  def leader_name(functionary)
    Functionary.find(functionary).name 
  end
  
end

app/views/functionaries/_form.html.erb
<%= form_with(model: functionary, local: true) do |form| %>

  <% if functionary.errors.any? 
    functionary.errors.full_messages.each do |message| %>
      <%= javascript_tag  "toastr['error']('#{message}')"  %>
    <%end%>
  <%end%>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :name %>
      <%= form.text_field :name, :class => "form-control"  %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= form.label :matriculation %>
      <%= form.text_field :matriculation, :class => "form-control"  %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :function %>      
      <%= form.select :function, Functionary::functions.collect { |key| [Functionary.human_attribute_name(key[0]), key[0]] }, {}, {:class => "form-control", :selected => 1}  %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :active %>
      <%= form.check_box :active, :class => "form-control"  %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :leader %>   
      <% options = options_from_collection_for_select(@list_leaders, 'id', 'name', @functionary.leader ) %>
      <%= form.select :leader,   options, {}, {:class => "form-control" }  %>
    </div>
  </div>

  <div class="row">
    <%= form.fields_for :user do |u| %>
      <div class="form-group col-md-4">
          <%= u.label :email %>
          <%= u.email_field :email,  autocomplete: "email", class: "form-control", placeholder: "Endereço de Email", required: "required" %>
      </div>
      <div class="form-group col-md-4">
        <%= u.label :password %>
        <%= u.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Senha" %>
      </div>
      <div class="form-group col-md-4">
        <%= u.label :password_confirmation %>
        <%= u.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Confirmar Senha" %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= link_to t('buttons.back'), functionaries_path, class:"btn btn-success" %>
    <%= submit_tag t('buttons.save'),  class:"btn btn-primary" %>
  </div>
  
<% end %>

app/views/functionaries/edit.html.erb
<div class="m-b-4">
  <h1 ><i class="fas  fa-users"></i>
    <%= " #{t('buttons.edit')} #{Functionary.model_name.human count: 1} " %>     
    <span class="badge badge-info " > <%= @functionary.id %></span>
  </h1>
</div>

<%= render 'form', functionary: @functionary %>

app/views/functionaries/index.html.erb
<h1 ><i class="fas  fa-users"></i> <%= Functionary.model_name.human count: 2 %></h1>

<% if can? :create, Functionary %>
  <%= link_to new_functionary_path do %>
        <span class="pull-left"><i class="far fa-lg  fa-plus-square"></i> <%= t('buttons.new') << ' ' << Functionary.model_name.human
  %> </span>
  <% end %>
<% end %>

<div  class="table-striped table-sm table-responsive table-hover mt-3">
  <table class="table">
    <caption> <%= page_entries_info @functionaries %></caption>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"><%= Functionary.human_attribute_name("matriculation")%></th>
        <th scope="col"><%= Functionary.human_attribute_name("name")%></th>
        <th scope="col"><%= Functionary.human_attribute_name("active")%></th>
      </tr>
    </thead>
    <tbody>
      <% @functionaries.each do |functionary| %>
        <tr  class='clickable-row' data-href='<%=  functionary_path(functionary) %>'>
          <td scope="row"><%= functionary.id %> </td>
          <td><%= functionary.matriculation %></td>
          <td><%= functionary.name %></td>
          <td><%= render inline: active_icon(functionary.active) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-12" >
    <%= paginate @functionaries %>
  </div>
</div>

app/views/functionaries/new.html.erb
<h1><i class="fas fa-users"></i><%= " Novo(a) #{Functionary.model_name.human}" %></h1>
<%= render 'form', functionary: @functionary %>

app/views/functionaries/show.html.erb
<div class="m-b-4">
  <h1 ><i class="fas fa-users"></i>
    <%= " #{Functionary.model_name.human count: 1} " %>     
    <span class="badge badge-info " > <%= @functionary.id %></span>
  </h1>
</div>

<p>
  <strong><%= Functionary.human_attribute_name("matriculation") %>: </strong>
  <%= @functionary.matriculation %>
</p>

<p>
  <strong><%= Functionary.human_attribute_name("name") %>: </strong>
  <%= @functionary.name %>
</p>

<p>
  <strong><%= Functionary.human_attribute_name("function") %>: </strong>
  <%= Functionary.human_attribute_name(@functionary.function) %>
</p>

<p>
  <strong><%= Functionary.human_attribute_name("leader") %>: </strong>
  <%= leader_name(@functionary.leader) %>
</p>

<p>
  <strong><%= Functionary.human_attribute_name("email") %>: </strong>
  <%= @functionary.user.email %>
</p>

<p>
  <strong><%= Functionary.human_attribute_name("active") %>: </strong>
  <%= render inline: active_icon(@functionary.active) %>
</p>


<div  class="table-striped table-sm table-responsive table-hover mt-3">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"><%= Car.human_attribute_name("plate")%></th>
        <th scope="col"><%= Car.human_attribute_name("mark")%></th>
        <th scope="col"><%= Car.human_attribute_name("modelType")%></th>
        <th scope="col"><%= Car.human_attribute_name("km")%></th>
      </tr>
    </thead>
    <tbody>
      <% @functionary.cars.each do |car| %>
        <tr  class='clickable-row' data-href='<%=  car_path(car) %>'>
          <td scope="row"><%= car.id %> </td>
          <td><%= car.plate %></td>
          <td><%= car.mark %></td>
          <td><%= car.modelType %></td>
          <td><%= car.km %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="form-group  text-center d-print-none ">

  <% if can? :index, Functionary %>
    <%= link_to t('buttons.back'), functionaries_path, class:"btn btn-sm btn-success" %>
  <% end %>
  <% if can? :edit, Functionary %>
    <%= link_to t('buttons.edit'), edit_functionary_path(@functionary), class:"btn btn-sm btn-primary" %>
  <% end %>
  <% if can? :destroy, Functionary %>
    <%= link_to t('buttons.delete'), functionary_path(@functionary), method: :delete, data: { confirm:   I18n.t('messages.confirm_with',item: " #{Functionary.model_name.human}: #{@functionary.name} " )}, class: "btn btn-sm btn-danger" %>
  <% end %>
</div>
    