config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root :to => "displacements#index" 

  resources :displacements
  resources :cars
  resources :addresses
  resources :functionaries


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :functionary
  has_many :displacements

  validates :plate, :mark, :modelType, :km, presence: true
  validates_format_of :plate, with: /\w{3}-\d{4}/
  validates_numericality_of :km

 #scope :with_car, ->(current_user){includes(:functionary).joins("INNER JOIN functionaries ON functionaries.id = cars.functionary_id").where("functionary_id = ? OR leader = ?", current_user, current_user)}
  scope :with_car, ->(current_user){
    includes(:functionary).left_joins(:functionary)
    .where('functionary_id = ? or leader = ?', current_user, current_user)
    .order('functionaries.name')
  }
    
  def to_s_select
    to_s(:select)
  end
  

  def full_car_name    
    "#{self.mark} #{self.modelType} - #{self.plate} "
  end

  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy, :km]
  before_action :lists_selects, only: [:edit, :update, :create, :new]

  #Cancancan
  load_and_authorize_resource
  
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.with_car(current_user).page params[:page]
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: I18n.t('messages.created_with', item: (Car.model_name.human count: 1) ) }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: I18n.t('messages.updated_with', item: (Car.model_name.human count: 1)  )}
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url,  notice: I18n.t('messages.destroyed_with', item: (Car.model_name.human count: 1) )}
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:plate, :mark, :modelType, :functionary_id, :km)
    end
      
    def lists_selects
      @list_functionaries = Functionary.with_functionary(current_user).select(:id, :name)
    end
  
end

app/helpers/cars_helper.rb
module CarsHelper

  def full_car(car)
    "#{car.mark} #{car.modelType} - Placa: #{car.plate}"
  end  

end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
      <% car.errors.full_messages.each do |message| %>
        <%= javascript_tag  "toastr['error']('#{message}')"  %>
      <% end %>
  <% end %>

  <div class="form-row">

    <div class="form-group col-md-3">
      <%= form.label :mark %>
      <%= form.text_field :mark, :class => "form-control", placeholder: "FORD, FIAT, CHEVROLLET"   %>
    </div>

    <div class="form-group col-md-3">
      <%= form.label :modelType %>
      <%= form.text_field :modelType, :class => "form-control", placeholder: "K 1.0, Pálio 1.4, GOL 1.6"  %>
    </div>

    <div class="form-group col-md-3">
      <%= form.label :plate %>
      <%= form.text_field :plate, :class => "form-control", placeholder: "ABC-1234"  %>
    </div>

    <div class="form-group col-md-3">
      <%= form.label :km %>
      <%= form.text_field :km, :class => "form-control", placeholder: "12505"  %>
    </div>

 </div>
  <div class="row">
    
    <div class="form-group col-md-12">
     <%= form.label :functionary_id %>
     <% options = options_from_collection_for_select(@list_functionaries, 'id', 'name', @car.functionary_id) %>
     <%= form.select :functionary_id,   options, {}, {:class => "form-control"}  %>
    </div>
</div>

  <div class="form-group">
    <%= link_to t('buttons.back'), cars_path, class:"btn btn-success" %>
    <%= submit_tag t('buttons.save'),  class:"btn btn-primary" %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<div class="m-b-4">
  <h1 ><i class="fas fa-car"></i>
    <%= " #{t('buttons.edit')} #{Car.model_name.human count: 1} " %>     
    <span class="badge badge-info " > <%= @car.id %></span>
  </h1>
</div>

<%= render 'form', car: @car %>

app/views/cars/index.html.erb
<h1><i class="fas   fa-car"></i> <%= Car.model_name.human count: 2 %></h1>

<% if can? :create, Car %>
  <%= link_to new_car_path do %>
        <span class="pull-left"><i class="far fa-lg  fa-plus-square"></i> <%= t('buttons.new') << ' ' << Car.model_name.human
  %> </span>
  <% end %>
<% end %>

<div  class="table-striped table-sm table-responsive table-hover mt-3">
  <table class="table">
   <caption> <%= page_entries_info @cars %></caption>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"><%= Car.human_attribute_name("plate")%></th>
        <th scope="col"><%= Car.human_attribute_name("mark")%></th>
        <th scope="col"><%= Car.human_attribute_name("modelType")%></th>
        <th scope="col"><%= Car.human_attribute_name("km")%></th>
        <% if %w[leader].include? current_user.functionary.function %> 
          <th scope="col"><%= Functionary.human_attribute_name("name")%></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @cars.each do |car| %>
        <tr  class='clickable-row' data-href='<%=  car_path(car) %>'>
          <td scope="row"><%= car.id %> </td>
          <td><%= car.plate %></td>
          <td><%= car.mark %></td>
          <td><%= car.modelType %></td>
          <td><%= car.km %></td>
          <% if %w[leader].include? current_user.functionary.function %> 
            <td><%= car.functionary.name %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-12" >
    <%= paginate @cars %>
  </div>
</div>

app/views/cars/new.html.erb
<h1><i class="fas fa-car"></i><%= " Novo #{Car.model_name.human}" %></h1>

<%= render 'form', car: @car %>

app/views/cars/show.html.erb
<div class="m-b-4">
  <h1 ><i class="fas fa-car"></i>
    <%= " #{Car.model_name.human count: 1} " %>     
    <span class="badge badge-info " > <%= @car.id %></span>
  </h1>
</div>

<p>
  <strong><%= Car.human_attribute_name("plate")%>: </strong>
  <%= @car.plate %>
</p>

<p>
  <strong><%= Car.human_attribute_name("mark")%>: </strong>
  <%= @car.mark %>
</p>

<p>
  <strong><%= Car.human_attribute_name("modelType")%>: </strong>
  <%= @car.modelType %>
</p>

<p>
  <strong><%= Car.human_attribute_name("km")%>: </strong>
  <%= @car.km %>
</p>
<p>
  <strong><%= Car.human_attribute_name("functionary_id")%>: </strong>
  <%= link_to functionary_path(@car.functionary) do
    @car.functionary.name
  end %>
</p>


<div class="form-group  text-center d-print-none ">
  <% if can? :index, Car %>
    <%= link_to t('buttons.back'), cars_path, class:"btn btn-sm btn-success" %>
  <% end %>

  <% if can? :update, Car %>
    <%= link_to t('buttons.edit'), edit_car_path(@car), class:"btn btn-sm btn-primary" %>
  <% end %>

  <% if can? :destroy, Car %>
    <%= link_to t('buttons.delete'), car_path(@car), method: :delete, data: { confirm:   I18n.t('messages.confirm_with',item: " #{Car.model_name.human}: #{full_car(@car)} " )}, class: "btn btn-sm btn-danger" %>
  <% end %>
</div>
    