config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root :to => "displacements#index" 

  resources :displacements
  resources :cars
  resources :addresses
  resources :functionaries


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/_footer.html.erb
  
<div class="container">
  <span class="text-muted">  <i class="fas fa-lg  fa-laptop-code"></i>
    Development by <%= link_to  'Geraldo Júnior', 'https://about.me/geraldo.junior', {:target => '_blank'} %> 
    for <%= link_to 'Solutis Tecnologias','http://solutis.com.br/',{:target => '_blank'} %> - <%= l Time.current %>.
  </span>
</div>

app/views/layouts/_navigation.html.erb
<!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md fixed-top nav-menu  ">

        <%= link_to root_path, :class => "navbar-brand mr-0 mr-md-2" do %>
           <%= image_tag("logo.png", height:"28" ) %>
        <% end %>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto ">

          <% if can? :index, Displacement %>
            <li class="nav-item">
              <%= link_to "Rotas", displacements_path, :class => "nav-link" << active_menu?('displacements')   %>
            </li>
          <% end %>

          <% if can? :index, Address %>
            <li class="nav-item">
              <%= link_to "Endereços", addresses_path, :class => "nav-link" << active_menu?('addresses') %>
            </li>
          <% end %>

          <% if can? :index, Car %>
            <li class="nav-item">
              <%= link_to "Carros", cars_path, :class => "nav-link" << active_menu?('cars') %>
            </li>
          <% end %>

          <% if can? :index, Functionary %>
            <li class="nav-item">
              <%= link_to "Funcionários", functionaries_path, :class => "nav-link" << active_menu?('functionaries')  %>
            </li>
          <% end %>

          <% if can? :index, Functionary %>
            <li class="nav-item">
              <%= link_to "Despesas", '#', :class => "nav-link" %>
            </li>
          <% end %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Links</a>
            <div class="dropdown-menu">  
              <%= link_to  "Hermes", "http://hermes.itoc.solutis.com.br", {class: "dropdown-item", target: "_blank", rel: "external"} %>
              <%= link_to  "Painel TJBA", "http://painel.tj.solutis.com.br", {class: "dropdown-item", target: "_blank", rel: "external"} %>
              <%= link_to  "Sapho", "http://sapho.solutis.com.br", {class: "dropdown-item", target: "_blank", rel: "external"} %>
              <%= link_to  "ServiceDesk TJBA", "http://servicedesk.tjba.jus.br/CAisd/pdmweb.exe", {class: "dropdown-item", target: "_blank", rel: "external"} %>
              <%= link_to  "ServiceDesk SEC", "http://servicedesk.sec.solutis.com.br", {class: "dropdown-item", target: "_blank", rel: "external"} %>
              <%= link_to  "ServiceDesk MP", "https://csti.sistemas.mpba.mp.br", {class: "dropdown-item", target: "_blank", rel: "external"} %>
              <%= link_to  "Webmail", "http://outlook.office.com/owa/?realm=solutis.com.br", {class: "dropdown-item", target: "_blank", rel: "external"} %>
 
	      <%= link_to "Portal RH", "https://portalrh.solutis.com.br" ,{class: "dropdown-item", target: "_blank", rel:"external"} %>
	      <div class="dropdown-divider"></div>   
              <%= link_to  "Solutis Tecnologias", "http://solutis.com.br/", {class: "dropdown-item", target: "_blank", rel: "external"} %>
 
            </div>
          </li>

          </ul>

          <ul class="nav navbar-nav navbar-right">
              <li class="nav-item"><%= current_user.email %> </li>
              <li class="nav-item">
                <%= link_to '#' do %>
                  <i class="fas fa-cog"></i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, :method => :delete do %>
                  <i class="fas fa-power-off"></i>
                <% end %>
              </li>

           </ul>
            
        </div>
      </nav>

app/views/layouts/_notifications.html.erb
<% if notice %>
  <%= javascript_tag "toastr['success']('#{notice}')" %>
<% end  %>

<% if alert %>
  <%= javascript_tag "toastr['error']('#{alert}')" %>
<% end  %>

<%= javascript_tag '
  toastr.options = {
          "closeButton": false,
          "debug": false,
          "newestOnTop": false,
          "progressBar": false,
          "positionClass": "toast-top-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        }
'%>

<%= devise_error_messages! %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Controle de KM para veículos terceirizados">
    <meta name="author" content="Solutis Tecnologias">
    <meta name="theme-color" content="#007bff">
    <meta name="apple-mobile-web-app-status-bar-style" content="#007bff">
    <meta name="msapplication-navbutton-color" content="#007bff">
          
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= favicon_link_tag 'serviceworker-rails/km-36x36.png' %>
   <!-- custom -->
    <%= stylesheet_link_tag    'application', media: 'all' %> 
    <!-- Font Aewsome -->
    <%= stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.2.0/css/all.css', {integrity: 'sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ', crossorigin:'anonymous'} %>   
    <!-- BootStrap 4 -->
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css', {integrity:'sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm', crossorigin:'anonymous'} %>
    <!-- Toastr -->
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css' %>   
    
  
    <!-- Custom -->
    <%= javascript_include_tag 'application' %>
    <!-- Fonte Awesomw -->
    <%= javascript_include_tag 'https://use.fontawesome.com/releases/v5.2.0/js/all.js', {integrity: 'sha384-4oV5EgaV02iISL2ban6c/RmotsABqE4yZxZLcYMAdG7FAPsyHYAPpywE9PJo+Khy', crossorigin:'anonymous'} %>
    <!-- Bootstrap -->
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js', {integrity:'sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q', crossorigin:'anonymous'}%>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js', {integrity:'sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl', crossorigin:'anonymous'} %>
       <!-- Toastr -->
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js' %>

  
  <title>Solutis - Suporte N2 </title>

  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>
  <body >   
    <header >
      <!-- Menu -->
      <%= render partial:"layouts/navigation" if user_signed_in? %>      
    </header>
    
    <!-- Begin page content -->
    <main role="main" class="container " style="margin-top:60px;">     
      <%= yield %>      
    </main>
    <footer class="footer">      
      <%= render partial:"layouts/footer" %> 
    </footer>    
             
    <%= render partial: 'layouts/notifications' %>
    
  <!-- Maps Google -->
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.credentials[Rails.env.to_sym][:google_key]}&callback=initMap", {:async => 'async', :defer => 'defer'} %>
 
  <%#= javascript_include_tag 'https://cdn.jsdelivr.net/npm/graphhopper-js-api-client/dist/graphhopper-client.js' %>

    
  </body>
  
  
</html>